version: "3.3"
services:
  app:
    build:
      context: . #current directory
      dockerfile: Dockerfile #use the dockerfile called Dockerfile
    ports:
      - "8080:8080" #forward port from my app to the OS
