// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package service

import (
	"salaries/pkg/api"
	"salaries/pkg/domain"
	"sync"
)

// Ensure, that SalaryServiceMock does implement SalaryService.
// If this is not the case, regenerate this file with moq.
var _ SalaryService = &SalaryServiceMock{}

// SalaryServiceMock is a mock implementation of SalaryService.
//
//	func TestSomethingThatUsesSalaryService(t *testing.T) {
//
//		// make and configure a mocked SalaryService
//		mockedSalaryService := &SalaryServiceMock{
//			CreateFunc: func(salary *domain.Salary) error {
//				panic("mock out the Create method")
//			},
//			DeleteByIDFunc: func(id int64) error {
//				panic("mock out the DeleteByID method")
//			},
//			GetAllFunc: func() ([]domain.Salary, error) {
//				panic("mock out the GetAll method")
//			},
//			GetContractsStatsFunc: func() (*api.Stats, error) {
//				panic("mock out the GetContractsStats method")
//			},
//			GetDepartmentsStatsFunc: func() ([]api.DepartmentStats, error) {
//				panic("mock out the GetDepartmentsStats method")
//			},
//			GetStatsForAllSalariesFunc: func() (*api.Stats, error) {
//				panic("mock out the GetStatsForAllSalaries method")
//			},
//			GetSubDepartmentsStatsFunc: func() ([]api.SubDepartmentStats, error) {
//				panic("mock out the GetSubDepartmentsStats method")
//			},
//		}
//
//		// use mockedSalaryService in code that requires SalaryService
//		// and then make assertions.
//
//	}
type SalaryServiceMock struct {
	// CreateFunc mocks the Create method.
	CreateFunc func(salary *domain.Salary) error

	// DeleteByIDFunc mocks the DeleteByID method.
	DeleteByIDFunc func(id int64) error

	// GetAllFunc mocks the GetAll method.
	GetAllFunc func() ([]domain.Salary, error)

	// GetContractsStatsFunc mocks the GetContractsStats method.
	GetContractsStatsFunc func() (*api.Stats, error)

	// GetDepartmentsStatsFunc mocks the GetDepartmentsStats method.
	GetDepartmentsStatsFunc func() ([]api.DepartmentStats, error)

	// GetStatsForAllSalariesFunc mocks the GetStatsForAllSalaries method.
	GetStatsForAllSalariesFunc func() (*api.Stats, error)

	// GetSubDepartmentsStatsFunc mocks the GetSubDepartmentsStats method.
	GetSubDepartmentsStatsFunc func() ([]api.SubDepartmentStats, error)

	// calls tracks calls to the methods.
	calls struct {
		// Create holds details about calls to the Create method.
		Create []struct {
			// Salary is the salary argument value.
			Salary *domain.Salary
		}
		// DeleteByID holds details about calls to the DeleteByID method.
		DeleteByID []struct {
			// ID is the id argument value.
			ID int64
		}
		// GetAll holds details about calls to the GetAll method.
		GetAll []struct {
		}
		// GetContractsStats holds details about calls to the GetContractsStats method.
		GetContractsStats []struct {
		}
		// GetDepartmentsStats holds details about calls to the GetDepartmentsStats method.
		GetDepartmentsStats []struct {
		}
		// GetStatsForAllSalaries holds details about calls to the GetStatsForAllSalaries method.
		GetStatsForAllSalaries []struct {
		}
		// GetSubDepartmentsStats holds details about calls to the GetSubDepartmentsStats method.
		GetSubDepartmentsStats []struct {
		}
	}
	lockCreate                 sync.RWMutex
	lockDeleteByID             sync.RWMutex
	lockGetAll                 sync.RWMutex
	lockGetContractsStats      sync.RWMutex
	lockGetDepartmentsStats    sync.RWMutex
	lockGetStatsForAllSalaries sync.RWMutex
	lockGetSubDepartmentsStats sync.RWMutex
}

// Create calls CreateFunc.
func (mock *SalaryServiceMock) Create(salary *domain.Salary) error {
	if mock.CreateFunc == nil {
		panic("SalaryServiceMock.CreateFunc: method is nil but SalaryService.Create was just called")
	}
	callInfo := struct {
		Salary *domain.Salary
	}{
		Salary: salary,
	}
	mock.lockCreate.Lock()
	mock.calls.Create = append(mock.calls.Create, callInfo)
	mock.lockCreate.Unlock()
	return mock.CreateFunc(salary)
}

// CreateCalls gets all the calls that were made to Create.
// Check the length with:
//
//	len(mockedSalaryService.CreateCalls())
func (mock *SalaryServiceMock) CreateCalls() []struct {
	Salary *domain.Salary
} {
	var calls []struct {
		Salary *domain.Salary
	}
	mock.lockCreate.RLock()
	calls = mock.calls.Create
	mock.lockCreate.RUnlock()
	return calls
}

// DeleteByID calls DeleteByIDFunc.
func (mock *SalaryServiceMock) DeleteByID(id int64) error {
	if mock.DeleteByIDFunc == nil {
		panic("SalaryServiceMock.DeleteByIDFunc: method is nil but SalaryService.DeleteByID was just called")
	}
	callInfo := struct {
		ID int64
	}{
		ID: id,
	}
	mock.lockDeleteByID.Lock()
	mock.calls.DeleteByID = append(mock.calls.DeleteByID, callInfo)
	mock.lockDeleteByID.Unlock()
	return mock.DeleteByIDFunc(id)
}

// DeleteByIDCalls gets all the calls that were made to DeleteByID.
// Check the length with:
//
//	len(mockedSalaryService.DeleteByIDCalls())
func (mock *SalaryServiceMock) DeleteByIDCalls() []struct {
	ID int64
} {
	var calls []struct {
		ID int64
	}
	mock.lockDeleteByID.RLock()
	calls = mock.calls.DeleteByID
	mock.lockDeleteByID.RUnlock()
	return calls
}

// GetAll calls GetAllFunc.
func (mock *SalaryServiceMock) GetAll() ([]domain.Salary, error) {
	if mock.GetAllFunc == nil {
		panic("SalaryServiceMock.GetAllFunc: method is nil but SalaryService.GetAll was just called")
	}
	callInfo := struct {
	}{}
	mock.lockGetAll.Lock()
	mock.calls.GetAll = append(mock.calls.GetAll, callInfo)
	mock.lockGetAll.Unlock()
	return mock.GetAllFunc()
}

// GetAllCalls gets all the calls that were made to GetAll.
// Check the length with:
//
//	len(mockedSalaryService.GetAllCalls())
func (mock *SalaryServiceMock) GetAllCalls() []struct {
} {
	var calls []struct {
	}
	mock.lockGetAll.RLock()
	calls = mock.calls.GetAll
	mock.lockGetAll.RUnlock()
	return calls
}

// GetContractsStats calls GetContractsStatsFunc.
func (mock *SalaryServiceMock) GetContractsStats() (*api.Stats, error) {
	if mock.GetContractsStatsFunc == nil {
		panic("SalaryServiceMock.GetContractsStatsFunc: method is nil but SalaryService.GetContractsStats was just called")
	}
	callInfo := struct {
	}{}
	mock.lockGetContractsStats.Lock()
	mock.calls.GetContractsStats = append(mock.calls.GetContractsStats, callInfo)
	mock.lockGetContractsStats.Unlock()
	return mock.GetContractsStatsFunc()
}

// GetContractsStatsCalls gets all the calls that were made to GetContractsStats.
// Check the length with:
//
//	len(mockedSalaryService.GetContractsStatsCalls())
func (mock *SalaryServiceMock) GetContractsStatsCalls() []struct {
} {
	var calls []struct {
	}
	mock.lockGetContractsStats.RLock()
	calls = mock.calls.GetContractsStats
	mock.lockGetContractsStats.RUnlock()
	return calls
}

// GetDepartmentsStats calls GetDepartmentsStatsFunc.
func (mock *SalaryServiceMock) GetDepartmentsStats() ([]api.DepartmentStats, error) {
	if mock.GetDepartmentsStatsFunc == nil {
		panic("SalaryServiceMock.GetDepartmentsStatsFunc: method is nil but SalaryService.GetDepartmentsStats was just called")
	}
	callInfo := struct {
	}{}
	mock.lockGetDepartmentsStats.Lock()
	mock.calls.GetDepartmentsStats = append(mock.calls.GetDepartmentsStats, callInfo)
	mock.lockGetDepartmentsStats.Unlock()
	return mock.GetDepartmentsStatsFunc()
}

// GetDepartmentsStatsCalls gets all the calls that were made to GetDepartmentsStats.
// Check the length with:
//
//	len(mockedSalaryService.GetDepartmentsStatsCalls())
func (mock *SalaryServiceMock) GetDepartmentsStatsCalls() []struct {
} {
	var calls []struct {
	}
	mock.lockGetDepartmentsStats.RLock()
	calls = mock.calls.GetDepartmentsStats
	mock.lockGetDepartmentsStats.RUnlock()
	return calls
}

// GetStatsForAllSalaries calls GetStatsForAllSalariesFunc.
func (mock *SalaryServiceMock) GetStatsForAllSalaries() (*api.Stats, error) {
	if mock.GetStatsForAllSalariesFunc == nil {
		panic("SalaryServiceMock.GetStatsForAllSalariesFunc: method is nil but SalaryService.GetStatsForAllSalaries was just called")
	}
	callInfo := struct {
	}{}
	mock.lockGetStatsForAllSalaries.Lock()
	mock.calls.GetStatsForAllSalaries = append(mock.calls.GetStatsForAllSalaries, callInfo)
	mock.lockGetStatsForAllSalaries.Unlock()
	return mock.GetStatsForAllSalariesFunc()
}

// GetStatsForAllSalariesCalls gets all the calls that were made to GetStatsForAllSalaries.
// Check the length with:
//
//	len(mockedSalaryService.GetStatsForAllSalariesCalls())
func (mock *SalaryServiceMock) GetStatsForAllSalariesCalls() []struct {
} {
	var calls []struct {
	}
	mock.lockGetStatsForAllSalaries.RLock()
	calls = mock.calls.GetStatsForAllSalaries
	mock.lockGetStatsForAllSalaries.RUnlock()
	return calls
}

// GetSubDepartmentsStats calls GetSubDepartmentsStatsFunc.
func (mock *SalaryServiceMock) GetSubDepartmentsStats() ([]api.SubDepartmentStats, error) {
	if mock.GetSubDepartmentsStatsFunc == nil {
		panic("SalaryServiceMock.GetSubDepartmentsStatsFunc: method is nil but SalaryService.GetSubDepartmentsStats was just called")
	}
	callInfo := struct {
	}{}
	mock.lockGetSubDepartmentsStats.Lock()
	mock.calls.GetSubDepartmentsStats = append(mock.calls.GetSubDepartmentsStats, callInfo)
	mock.lockGetSubDepartmentsStats.Unlock()
	return mock.GetSubDepartmentsStatsFunc()
}

// GetSubDepartmentsStatsCalls gets all the calls that were made to GetSubDepartmentsStats.
// Check the length with:
//
//	len(mockedSalaryService.GetSubDepartmentsStatsCalls())
func (mock *SalaryServiceMock) GetSubDepartmentsStatsCalls() []struct {
} {
	var calls []struct {
	}
	mock.lockGetSubDepartmentsStats.RLock()
	calls = mock.calls.GetSubDepartmentsStats
	mock.lockGetSubDepartmentsStats.RUnlock()
	return calls
}
